In [47]:
import pandas as pd

In [48]:
Df=pd.read_csv('sample_large_dirty_data.csv')

In [49]:
Df.head()

,Full Name,Gender,Country,DOB,AGE,Email
0,Norma Fisher,NaN,NaN,11-19-1971,20,thull@yahoo.com
1,Steven Robinson,FEMALE,United Kingdom,09-28-1963,43,katelynmontgomery@yahoo.com
2,Ms. Michele Guzman,NaN,Canada,04-06-1964,40,blairrachel@hotmail.com
3,Justin Gomez,F,U.S.,1975/10/13,36,hramos@brown-sellers.com
4,Ryan Page,male,usa,25/09/1999,52,vclayton@cross.com

In [50]:
Df.isnull().sum()

Full Name    10
Gender       81
 Country     88
DOB          10
 AGE         25
Email        10
dtype: int64

In [51]:
Df.dropna()

,Full Name,Gender,Country,DOB,AGE,Email
1,Steven Robinson,FEMALE,United Kingdom,09-28-1963,43,katelynmontgomery@yahoo.com
3,Justin Gomez,F,U.S.,1975/10/13,36,hramos@brown-sellers.com
4,Ryan Page,male,usa,25/09/1999,52,vclayton@cross.com
5,Keith Allen,M,United States,17/12/1963,24,millerluke@hotmail.com
6,Mrs. Elizabeth Carter MD,M,usa,27/11/1976,48,sean96@johnston-roberts.com
...,...,...,...,...,...,...
513,Stephanie Moore,male,Canada,11-10-1970,Twenty Five,gillbrian@steele.info
514,Sean Foster,F,U.S.,09-07-1973,41,ujohnson@fisher.com
516,Megan Lopez,FEMALE,usa,25/01/1978,67,michael94@gmail.com
518,Rodney Bowers,female,USA,1961/11/08,40,jensenmichael@yahoo.com
519,Vickie Noble,female,usa,02/06/1958,24,garygreer@gmail.com

In [52]:
df1=Df.duplicated().sum()
print(df1)

29

In [53]:
duplicates=Df[Df.duplicated()]
print(duplicates)

            Full Name Gender        Country          DOB          AGE  \
500        Jason Ward       M            USA  27/05/1993           68
501   Natasha Barrera    Male           U.S.  23-11-1984           60
502        David Diaz    Male         Canada  1974/11/05           42
503      Nicole Bowen    male            usa  17/12/1996           28
504     Emily Sanchez  FEMALE            NaN  19/08/2005           27
505    Brittney Lopez  FEMALE         canada  04-03-1995           38
506          Amy Cole  FEMALE             UK  06/11/1976           24
507      Carl Osborne       M            usa  25-07-1981           20
508        Paul Gomez    male           U.S.  08-28-2005           42
509  Cynthia Williams     NaN            NaN  10-05-1960           69
510    Lisa Mccormick     NaN  United States  26/08/2002          NaN
511    Gregory Carney    Male            NaN  04-01-1996           62
512       Penny Moore    male         Canada  23/01/1988           37
513   Stephanie Moore    male         Canada  11-10-1970  Twenty Five
514       Sean Foster       F           U.S.  09-07-1973           41
515    Gregory Carney    Male            NaN  04-01-1996           62
516       Megan Lopez  FEMALE            usa  25/01/1978           67
517    Michael Larson       M            NaN  10-08-1981           61
518     Rodney Bowers  female            USA  1961/11/08           40
519      Vickie Noble  female            usa  02/06/1958           24
521               NaN     NaN            NaN         NaN          NaN
522               NaN     NaN            NaN         NaN          NaN
523               NaN     NaN            NaN         NaN          NaN
524               NaN     NaN            NaN         NaN          NaN
525               NaN     NaN            NaN         NaN          NaN
526               NaN     NaN            NaN         NaN          NaN
527               NaN     NaN            NaN         NaN          NaN
528               NaN     NaN            NaN         NaN          NaN
529               NaN     NaN            NaN         NaN          NaN

                                Email
500           jasonwarren@hotmail.com
501          powersscott@campbell.com
502            ejones@long-benton.net
503                anavarro@rubio.com
504                nathan02@smith.biz
505                  eric29@yahoo.com
506             browndonna@prince.com
507                  tperez@yahoo.com
508  johnsonlaura@ferguson-wilson.com
509         cabreramonica@hotmail.com
510               dpalmer@hotmail.com
511              kingdalton@gmail.com
512             perezjasmine@wang.com
513             gillbrian@steele.info
514               ujohnson@fisher.com
515              kingdalton@gmail.com
516               michael94@gmail.com
517          martinpatricia@yahoo.com
518           jensenmichael@yahoo.com
519               garygreer@gmail.com
521                               NaN
522                               NaN
523                               NaN
524                               NaN
525                               NaN
526                               NaN
527                               NaN
528                               NaN
529                               NaN

In [54]:
Df.drop_duplicates()

,Full Name,Gender,Country,DOB,AGE,Email
0,Norma Fisher,NaN,NaN,11-19-1971,20,thull@yahoo.com
1,Steven Robinson,FEMALE,United Kingdom,09-28-1963,43,katelynmontgomery@yahoo.com
2,Ms. Michele Guzman,NaN,Canada,04-06-1964,40,blairrachel@hotmail.com
3,Justin Gomez,F,U.S.,1975/10/13,36,hramos@brown-sellers.com
4,Ryan Page,male,usa,25/09/1999,52,vclayton@cross.com
...,...,...,...,...,...,...
496,Jonathan Coleman,F,United States,04-11-2000,43,zachary83@medina.biz
497,Anthony Flores,FEMALE,United Kingdom,09-26-1957,32,williamsmith@hotmail.com
498,Lisa Russell,M,canada,28/01/1987,45,kellywright@gmail.com
499,Nancy Jarvis,FEMALE,canada,06-06-2006,67,jacob95@gmail.com
520,NaN,NaN,NaN,NaN,NaN,NaN

convert age to number

In [55]:
Df[' AGE'] = pd.to_numeric(Df[' AGE'], errors='coerce')

fill missing age with median

In [56]:
Df[' AGE'] = Df[' AGE'].fillna(Df[' AGE'].median())

In [57]:
Df.head(10)

,Full Name,Gender,Country,DOB,AGE,Email
0,Norma Fisher,NaN,NaN,11-19-1971,20.0,thull@yahoo.com
1,Steven Robinson,FEMALE,United Kingdom,09-28-1963,43.0,katelynmontgomery@yahoo.com
2,Ms. Michele Guzman,NaN,Canada,04-06-1964,40.0,blairrachel@hotmail.com
3,Justin Gomez,F,U.S.,1975/10/13,36.0,hramos@brown-sellers.com
4,Ryan Page,male,usa,25/09/1999,52.0,vclayton@cross.com
5,Keith Allen,M,United States,17/12/1963,24.0,millerluke@hotmail.com
6,Mrs. Elizabeth Carter MD,M,usa,27/11/1976,48.0,sean96@johnston-roberts.com
7,Amanda Zavala,F,usa,17/12/1971,45.0,daviskatherine@gmail.com
8,Sarah Villanueva,FEMALE,U.S.,01-19-1991,46.0,aimee33@hotmail.com
9,Tiffany Riley,NaN,United Kingdom,03/12/1984,21.0,christopher91@yahoo.com

Lower case and remove space

In [58]:
Df.columns = Df.columns.str.strip().str.lower().str.replace(' ', '_')

In [59]:
Df['country'] = Df['country'].str.strip().str.lower().replace({
    'usa': 'united states',
    'u.s.': 'united states',
    'united states': 'united states',
    'uk': 'united kingdom'
}).fillna('unknown')

In [60]:
Df.head(15)

,full_name,gender,country,dob,age,email
0,Norma Fisher,NaN,unknown,11-19-1971,20.0,thull@yahoo.com
1,Steven Robinson,FEMALE,united kingdom,09-28-1963,43.0,katelynmontgomery@yahoo.com
2,Ms. Michele Guzman,NaN,canada,04-06-1964,40.0,blairrachel@hotmail.com
3,Justin Gomez,F,united states,1975/10/13,36.0,hramos@brown-sellers.com
4,Ryan Page,male,united states,25/09/1999,52.0,vclayton@cross.com
5,Keith Allen,M,united states,17/12/1963,24.0,millerluke@hotmail.com
6,Mrs. Elizabeth Carter MD,M,united states,27/11/1976,48.0,sean96@johnston-roberts.com
7,Amanda Zavala,F,united states,17/12/1971,45.0,daviskatherine@gmail.com
8,Sarah Villanueva,FEMALE,united states,01-19-1991,46.0,aimee33@hotmail.com
9,Tiffany Riley,NaN,united kingdom,03/12/1984,21.0,christopher91@yahoo.com
10,Gabriela Lee,NaN,united kingdom,14-05-1955,23.0,thorntonnathan@gmail.com
11,Robert Garcia,M,unknown,22-03-1964,57.0,montoyacynthia@guzman.com
12,Laura Myers,female,canada,1979/06/14,64.0,jacobsjames@robbins.com
13,Amy Shelton,FEMALE,united states,1991/04/20,54.0,huffchad@gmail.com
14,Hayley White,male,united states,1988/07/14,69.0,carlsonholly@yahoo.com

for gender column it wil convert m to male and f to female

In [61]:
Df['gender'] = Df['gender'].str.strip().str.lower().replace({
    'm': 'male',
    'f': 'female',
    '': 'unknown',
    None: 'unknown'
}).fillna('unknown')

In [62]:
Df.head(10)

,full_name,gender,country,dob,age,email
0,Norma Fisher,unknown,unknown,11-19-1971,20.0,thull@yahoo.com
1,Steven Robinson,female,united kingdom,09-28-1963,43.0,katelynmontgomery@yahoo.com
2,Ms. Michele Guzman,unknown,canada,04-06-1964,40.0,blairrachel@hotmail.com
3,Justin Gomez,female,united states,1975/10/13,36.0,hramos@brown-sellers.com
4,Ryan Page,male,united states,25/09/1999,52.0,vclayton@cross.com
5,Keith Allen,male,united states,17/12/1963,24.0,millerluke@hotmail.com
6,Mrs. Elizabeth Carter MD,male,united states,27/11/1976,48.0,sean96@johnston-roberts.com
7,Amanda Zavala,female,united states,17/12/1971,45.0,daviskatherine@gmail.com
8,Sarah Villanueva,female,united states,01-19-1991,46.0,aimee33@hotmail.com
9,Tiffany Riley,unknown,united kingdom,03/12/1984,21.0,christopher91@yahoo.com

for email column

In [63]:
Df['email'] = Df['email'].str.strip().str.lower().fillna('unknown')

In [64]:
Df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_name  520 non-null    object
 1   gender     530 non-null    object
 2   country    530 non-null    object
 3   dob        520 non-null    object
 4   age        530 non-null    float64
 5   email      530 non-null    object
dtypes: float64(1), object(5)
memory usage: 25.0+ KB

In [65]:
Df.duplicated().sum()

np.int64(29)

In [66]:
Df.head(10)

,full_name,gender,country,dob,age,email
0,Norma Fisher,unknown,unknown,11-19-1971,20.0,thull@yahoo.com
1,Steven Robinson,female,united kingdom,09-28-1963,43.0,katelynmontgomery@yahoo.com
2,Ms. Michele Guzman,unknown,canada,04-06-1964,40.0,blairrachel@hotmail.com
3,Justin Gomez,female,united states,1975/10/13,36.0,hramos@brown-sellers.com
4,Ryan Page,male,united states,25/09/1999,52.0,vclayton@cross.com
5,Keith Allen,male,united states,17/12/1963,24.0,millerluke@hotmail.com
6,Mrs. Elizabeth Carter MD,male,united states,27/11/1976,48.0,sean96@johnston-roberts.com
7,Amanda Zavala,female,united states,17/12/1971,45.0,daviskatherine@gmail.com
8,Sarah Villanueva,female,united states,01-19-1991,46.0,aimee33@hotmail.com
9,Tiffany Riley,unknown,united kingdom,03/12/1984,21.0,christopher91@yahoo.com

In [67]:
Df.dtypes

full_name     object
gender        object
country       object
dob           object
age          float64
email         object
dtype: object

In [68]:
Df.head(15)

,full_name,gender,country,dob,age,email
0,Norma Fisher,unknown,unknown,11-19-1971,20.0,thull@yahoo.com
1,Steven Robinson,female,united kingdom,09-28-1963,43.0,katelynmontgomery@yahoo.com
2,Ms. Michele Guzman,unknown,canada,04-06-1964,40.0,blairrachel@hotmail.com
3,Justin Gomez,female,united states,1975/10/13,36.0,hramos@brown-sellers.com
4,Ryan Page,male,united states,25/09/1999,52.0,vclayton@cross.com
5,Keith Allen,male,united states,17/12/1963,24.0,millerluke@hotmail.com
6,Mrs. Elizabeth Carter MD,male,united states,27/11/1976,48.0,sean96@johnston-roberts.com
7,Amanda Zavala,female,united states,17/12/1971,45.0,daviskatherine@gmail.com
8,Sarah Villanueva,female,united states,01-19-1991,46.0,aimee33@hotmail.com
9,Tiffany Riley,unknown,united kingdom,03/12/1984,21.0,christopher91@yahoo.com
10,Gabriela Lee,unknown,united kingdom,14-05-1955,23.0,thorntonnathan@gmail.com
11,Robert Garcia,male,unknown,22-03-1964,57.0,montoyacynthia@guzman.com
12,Laura Myers,female,canada,1979/06/14,64.0,jacobsjames@robbins.com
13,Amy Shelton,female,united states,1991/04/20,54.0,huffchad@gmail.com
14,Hayley White,male,united states,1988/07/14,69.0,carlsonholly@yahoo.com

In [69]:
Df.tail(25)

,full_name,gender,country,dob,age,email
505,Brittney Lopez,female,canada,04-03-1995,38.0,eric29@yahoo.com
506,Amy Cole,female,united kingdom,06/11/1976,24.0,browndonna@prince.com
507,Carl Osborne,male,united states,25-07-1981,20.0,tperez@yahoo.com
508,Paul Gomez,male,united states,08-28-2005,42.0,johnsonlaura@ferguson-wilson.com
509,Cynthia Williams,unknown,unknown,10-05-1960,69.0,cabreramonica@hotmail.com
510,Lisa Mccormick,unknown,united states,26/08/2002,44.0,dpalmer@hotmail.com
511,Gregory Carney,male,unknown,04-01-1996,62.0,kingdalton@gmail.com
512,Penny Moore,male,canada,23/01/1988,37.0,perezjasmine@wang.com
513,Stephanie Moore,male,canada,11-10-1970,44.0,gillbrian@steele.info
514,Sean Foster,female,united states,09-07-1973,41.0,ujohnson@fisher.com
515,Gregory Carney,male,unknown,04-01-1996,62.0,kingdalton@gmail.com
516,Megan Lopez,female,united states,25/01/1978,67.0,michael94@gmail.com
517,Michael Larson,male,unknown,10-08-1981,61.0,martinpatricia@yahoo.com
518,Rodney Bowers,female,united states,1961/11/08,40.0,jensenmichael@yahoo.com
519,Vickie Noble,female,united states,02/06/1958,24.0,garygreer@gmail.com
520,NaN,unknown,unknown,NaN,44.0,unknown
521,NaN,unknown,unknown,NaN,44.0,unknown
522,NaN,unknown,unknown,NaN,44.0,unknown
523,NaN,unknown,unknown,NaN,44.0,unknown
524,NaN,unknown,unknown,NaN,44.0,unknown
525,NaN,unknown,unknown,NaN,44.0,unknown
526,NaN,unknown,unknown,NaN,44.0,unknown
527,NaN,unknown,unknown,NaN,44.0,unknown
528,NaN,unknown,unknown,NaN,44.0,unknown
529,NaN,unknown,unknown,NaN,44.0,unknown

In [74]:
df.to_csv('cleaned_data.csv', index=False)

In [75]:
from google.colab import files
files.download('cleaned_data.csv')

In [72]:
import pandas as pd, io
csv_data = Df.to_csv(index=False)
df = pd.read_csv(io.StringIO(csv_data))
df.head()

,full_name,gender,country,dob,age,email
0,Norma Fisher,unknown,unknown,11-19-1971,20.0,thull@yahoo.com
1,Steven Robinson,female,united kingdom,09-28-1963,43.0,katelynmontgomery@yahoo.com
2,Ms. Michele Guzman,unknown,canada,04-06-1964,40.0,blairrachel@hotmail.com
3,Justin Gomez,female,united states,1975/10/13,36.0,hramos@brown-sellers.com
4,Ryan Page,male,united states,25/09/1999,52.0,vclayton@cross.com